name: .NET Core + Testes + Azure Functions 3.x

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CAMINHO_PROJETO_TESTES: ./ServerlessTemperatura.Testes/ServerlessTemperatura.Testes.csproj
      DIRETORIO_WEBAPP: ./ServerlessTemperatura
      FUNCTION_APP: groffetemperatura

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Executar testes automatizados
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal
      
    - name: Build com o utilitario dotnet
      run: dotnet build ${{ env.DIRETORIO_WEBAPP }} --configuration Release

    - name: Publish com o utilitario dotnet
      run: dotnet publish ${{ env.DIRETORIO_WEBAPP }} -c Release -o app

    - name: Azure Login - Conectando com Credenciais no Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure Functions - Deployment da Function App
      uses: Azure/functions-action@v1.1.5
      with:
        app-name: ${{ env.FUNCTION_APP }}
        package: './app'